package com.jjkeller.kmbapi.geotab.implementation.enums;

public enum AssertStatusDefinition {
    BASE_INFO,
    SUCCESS,
    INVALID_STATE,
    VALIDATOR_DEFINITION_NOT_FOUND,
    EXPECTED_END_EVENTRECORD_MISMATCH,
    EXPECTED_END_EVENT_FOUND_NONE,
    EXPECTED_NO_RESULT_FOUND_RESULT,
    EXPECTED_RESULT_FOUND_NONE

}