package com.jjkeller.kmbapi.enums;

public enum USBAccessoryConnectionStatus
{
    CONNECTED, REQUESTING_PERMISSION, UNKNOWN_ACCESSORY, NO_ACCESSORY, NO_PARCEL, DISONNECTED, ACCESSORY_DETECTED, PERMISSION_TIMEOUT, PERMISSION_DENIED
}